export const actionTypes = {
    LOGIN: "LOGIN",
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    GET_CURRENT_PROFILE: 'GET_CURRENT_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    GET_GARAGE_INFOR: 'GET_GARAGE_INFOR',
    UPDATE_GARAGE_INFOR: 'UPDATE_GARAGE_INFOR',

    GET_ALL_BOOKING_GARAGE: 'GET_ALL_BOOKING_GARAGE',
    GARAGE_DELETE_BOOKING: 'GARAGE_DELETE_BOOKING',
    UPDATE_BOOKING_STATUS: 'UPDATE_BOOKING_STATUS',
    CREATE_BOOKING: 'CREATE_BOOKING',
    CANCEL_BOOKING: 'CANCEL_BOOKING',
    GET_ALL_BOOKING_CUSTOMER: 'GET_ALL_BOOKING_CUSTOMER',
    ADD_GARAGE_BOOKING: 'ADD_GARAGE_BOOKING',
    CREATE_INVOICE: 'CREATE_INVOICE',

    GET_POST: 'GET_POST',
    GET_NEW_POST: 'GET_NEW_POST',
    GET_CARS: 'GET_CARS',
    CREATE_CAR: 'CREATE_CAR',
    DELETE_CAR: 'DELETE_CAR',

    GET_MECHANICS: 'GET_MECHANICS',

}