export const actionTypes = {
    LOGIN: "LOGIN",
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    GET_CURRENT_PROFILE: 'GET_CURRENT_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE'
}